# Generated by Django 5.0.4 on 2024-04-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('street', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='media/students/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('b', 'B'), ('m', 'M'), ('ph', 'PH')], default='b', max_length=30)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.address')),
            ],
        ),
    ]
